on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      filurl:
        description: '下载地址'
        required: true
        default: ''
      filename:
        description: '文件名称'
        required: true
        default: ''

name: RUN
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: download
      run: |
        mkdir -p $PWD/dw/
        curl -o $PWD/dw/${{ github.event.inputs.filename }} ${{ github.event.inputs.filurl }}

    - name: Release set path
      run: |
        md5sum $PWD/dw/*>release.txt
        echo "RELEASE_PATH=$PWD/dw/" >> $GITHUB_ENV
        echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.FILE_DATE }}_${{ github.event.inputs.filename }}
        body_path: release.txt
        files: ${{ env.RELEASE_PATH }}/*
