on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      filurl:
        description: '下载地址'
        required: true
        default: ''
      filename:
        description: '文件名称'
        required: true
        default: ''
      option:
        description: '选择类型'
        required: true
        default: 'aria2c'
        type: choice
        options:
          - 'aria2c'
          - 'curl'
          - 'wget'

name: RUN
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: download
      if: ${{ github.event.inputs.option == 'curl' }}
      run: |
        sudo apt-get install coreutils aria2 -y
        mkdir -p $PWD/dw/
        curl -o $PWD/dw/${{ github.event.inputs.filename }} "${{ github.event.inputs.filurl }}"
    - name: download
      if: ${{ github.event.inputs.option == 'wget' }}
      run: |
        mkdir -p $PWD/dw/
        wget -O $PWD/dw/${{ github.event.inputs.filename }} "${{ github.event.inputs.filurl }}"
    - name: download
      if: ${{ github.event.inputs.option == 'aria2c' }}
      run: |
        mkdir -p $PWD/dw/
        aria2c -d $PWD/dw/ -o ${{ github.event.inputs.filename }} "${{ github.event.inputs.filurl }}"
    - name: Release set path
      run: |
        touch release.txt
        echo "${{ github.event.inputs.filurl }}">>release.txt
        sha256sum $PWD/dw/*>>release.txt
        ls -la $PWD/dw/*>>release.txt
        echo "RELEASE_PATH=$PWD/dw/" >> $GITHUB_ENV
        echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.FILE_DATE }}_${{ github.event.inputs.filename }}
        body_path: release.txt
        files: ${{ env.RELEASE_PATH }}/*
